azure blob storageのコンテナ操作の実装
futaringoto/futarin-api pull request #169
Opened 2024-10-02 12:08 UTC by harudra

## 概要
user作成後にコンテナを作ることと、user削除後にコンテナも同時に消すことの実装が終わりました。

## 関連タスク
Close #166 

## やったこと
コンテナ名は'user{user_id}としています。

## やらないこと

## レビュー事項
-

## 補足 参考情報

2024-10-02 13:05 UTC, shun-harutaro requested changes

2024-10-02 13:05 UTC, shun-harutaro commented on api/v2/routers/user.py
> +account_url = "https://futarinstorageaccount.blob.core.windows.net"
`futarinstorageaccount` は`STORAGE_ACCOUNT_NAME`という環境変数にして欲しい（一応秘匿しておきたい）

2024-10-02 13:05 UTC, shun-harutaro commented on api/v2/schemas/user.py
> +    # model_config = {"orm_mode": True}
これ消してー

2024-10-02 13:05 UTC, shun-harutaro commented on api/v2/utils/config.py
> +    return os.getenv("AZURE_SAS_TOKEN")
👍

2024-10-02 13:05 UTC, shun-harutaro commented on api/v2/cruds/user.py
`blob_service_client`を引数で受け取るようにしているのめっちゃいいね！設計の分離ができてます 👍

2024-10-02 13:07 UTC, shun-harutaro requested changes
CI でビルドが完了してないね。poetry 周りのエラーが出てる。
レビューの修正と、忘れずリント・整形してからpushよろです。

2024-10-02 13:21 UTC, harudra commented
CIのビルドって何ですか

2024-10-03 09:11 UTC, shun-harutaro commented
バッチリ

2024-10-03 21:40 UTC, shun-harutaro approved these changes
LGTM 👍

2024-10-04 22:56 UTC, merged